### ISSUE TITLE
Add napi-rs for Node.js FFI

### ISSUE THREAD

**Issue by ssokolow** [areweextendingyet/areweextendingyet.github.io#4]
[napi-rs](https://github.com/napi-rs/napi-rs) is listed on [the other list of FFI crates](https://www.hobofan.com/rust-interop/) and, according to [this Reddit comment](https://www.reddit.com/r/rust/comments/ix2a9m/what_are_the_difference_to_those_approach_when/g67iv0a/) it can do threading while that's still an [open issue](https://github.com/neon-bindings/neon/issues/197) for Neon.

**Comment by bltavares** [comment]
Thank you for sharing the new project.
